// FFI over the Rust/WASM force-simulation engine (fluent-wasm crate). The
// wasm bytes are inlined at build time (fluent-wasm.js, generated by
// scripts/build-wasm.mjs), mirroring how viz.js ships its WASM: no runtime
// fetch, no CSP connect-src, works under default-src 'none'.
//
// The path below is resolved by esbuild FROM output-es/Webview.Fluent/
// (purs-backend-es copies only foreign.js), pointing back at the source tree.
import { fluentWasmBase64 } from "../../webview-src/src/Webview/fluent-wasm.js";

// The wasm exports shaped as the PureScript `Engine` record. Every field
// returns an Effect thunk: wasm functions return undefined, so passing them
// through directly would make PureScript call that undefined as the Effect.
// readX/readY build a fresh view per call — a cached one reads stale
// positions across frames.
function toEngine(ex) {
  const read = (ptr) => (i) => () => new Float32Array(ex.memory.buffer, ptr(), ex.node_count())[i];
  return {
    configure: (nodes, edges) => () => ex.configure(nodes, edges),
    setEdge: (k, a, b) => () => ex.set_edge(k, a, b),
    setMouse: (x, y, active) => () => ex.set_mouse(x, y, active),
    grab: (i) => () => ex.grab(i),
    release: () => ex.release(),
    step: (dt) => () => ex.step(dt),
    readX: read(ex.px_ptr),
    readY: read(ex.py_ptr),
  };
}

// Callback-style bridge (purs-viz shape); PureScript owns caching/policy.
export function _startEngine(onSuccess) {
  return (onFailure) => () => {
    const bin = atob(fluentWasmBase64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i += 1) bytes[i] = bin.charCodeAt(i);
    WebAssembly.instantiate(bytes, {})
      .then(
        (result) => onSuccess(toEngine(result.instance.exports))(),
        (err) => onFailure(String(err))()
      )
      // never let a callback failure reject unhandled (kills the host)
      .catch(() => {});
  };
}
