// Rebuild the fluent-panel wasm engine and regenerate the checked-in base64
// module consumed by the webview (webview-src/src/Webview/fluent-wasm.js).
// CI and `npm run compile` do NOT run this — they consume the committed
// artifact — so a machine without cargo can still build and package the
// extension. Requires: rustup with the wasm32-unknown-unknown target
// (`rustup target add wasm32-unknown-unknown`).
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const cargo = process.env.CARGO ?? join(process.env.HOME ?? "~", ".cargo/bin/cargo");

execFileSync(cargo, ["build", "--release", "--target", "wasm32-unknown-unknown"], {
  cwd: join(root, "fluent-wasm"),
  stdio: "inherit",
});

const wasmPath = join(root, "fluent-wasm/target/wasm32-unknown-unknown/release/fluent_wasm.wasm");
const wasm = readFileSync(wasmPath);
const out = `// GENERATED by scripts/build-wasm.mjs (npm run wasm) — do not edit.
export const fluentWasmBase64 = "${wasm.toString("base64")}";
`;
writeFileSync(join(root, "webview-src/src/Webview/fluent-wasm.js"), out);
console.log(`wrote webview-src/src/Webview/fluent-wasm.js (${wasm.length} wasm bytes)`);
